### PR TITLE
rngd_jitter: make timeout configurable

### PR DESCRIPTION
**Pull request by sharkcz**
The current default 5 sec timeout can be too short in some situations
(eg. slow hardware). Introduce an enviroment variable
RNGD_JITTER_TIMEOUT to make the value configurable. Increasing the
default timeout is not desirable, because it might slow down system
startup when there are other entropy sources.

### CODE REVIEW

**Comment by nhorman** [comment]
why an environment variable instead of an option?  An option would be in keeping with how we handle entropy specific behavior.  See JITTER_OPT_THREADS and friends in rngd.c for examples.

**Comment by sharkcz** [comment]
> why an environment variable instead of an option? An option would be in keeping with how we handle entropy specific behavior. See JITTER_OPT_THREADS and friends in rngd.c for examples.

because that was the first idea (https://github.com/nhorman/rng-tools/issues/174#issuecomment-1171401748) how to allow changing the timeout with minimal (or zero) changes in other code to get the tests passing. But you are right, an option would work too, together with a slight update to the test script.

**Comment by sharkcz** [comment]
Reworked to use command line option instead.

Do you want the test change be a separate commit?

**Comment by nhorman** [comment]
nah, single commit is fine @sharkcz .  This looks much better, thanks!

**Pull request merged**
